# -*- coding: utf-8 -*-
# Generated by Django 1.9c2 on 2015-11-27 11:26
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='properties',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
