# -*- coding: utf-8 -*-
# Generated by Django 1.9c2 on 2015-11-27 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20151127_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='order',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='productfield',
            name='order',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
